config/routes.rb
Rails.application.routes.draw do
  get 'users/history'

  devise_for :users
  resources :items do
    member do
      get'purchase'
    end
  end

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_and_belongs_to_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :purchase]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    @item.stock -= 1
    @item.save
    current_user.items << @item
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :stock)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<h1>これはああああああああ</h1>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div> 
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class= "container">

<h1>商品一覧</h1>

<div class='row text-right'>
    <% if current_user %>
    ようこそ<%= current_user.email %>さん
    あなたのidは<%= current_user.id %>です。
      <%= link_to 'ログアウト', destroy_user_session_path, class: 'btn btn-danger', method: :delete %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-danger' %>
      <%= link_to '新規登録', new_user_registration_path, class: 'btn btn-warning' %>

    <% end %>
</div>


    <div class='row text-center'>
      <% @items.each do |item| %>
            <div class='col-md-12'>
              <%= image_tag "coffee.jpg", width: '400px' %>
              <h1><%= item.name %></h1>
              <p><%= item.price %>円 在庫数：<%= item.stock %> </p>
            </div>
            <% if current_user %>
              <p><%= link_to '購入', purchase_item_path(item), class: "btn btn-primary", data: { confirm: '購入しますか？' } %>
                <% end %>
              <%= link_to '商品ページ', item, class: "btn btn-warning" %>
              <%= link_to 'Edit', edit_item_path(item), class: "btn btn-default" %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></p>
      <% end %>
    </div>

<br>

<div class='row'>
  <div class='col-md-12'>
<h2>現在のユーザーの数は<%= User.count %>人です。</h2>
<p><% User.all.each do |user| %></p>
<p><%= user.email %></p>
<% end %>
</div>
</div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/purchase.html.erb
<div class="row">
  <div class="col-md-12">
<h1><%= @item.name %>を購入しました。</h1>
<h2>残りの在庫数は<%= @item.stock %>です。</h2>
<p><%= link_to '購入履歴へ', users_history_path, class: "btn btn-warning"%> <p/>

app/views/items/show.html.erb
<div class="row text-center">
  <div class="col-md-12">
    <%= image_tag 'coffee.jpg', width: '400px' %>
    <h3><%= @item.name %></h3>
    <p><%= @item.price %>円 - 在庫数:<%= @item.stock %></p>
  </div>
  <% if current_user %>
    <%= link_to '購入', purchase_item_path(@item), data: { confirm: '本当に購入しますか？' }, class: 'btn btn-warning' %>
  <% else %>
    ログインをして購入してください。
  <% end %>
</div>

<% @item.users.each do |user| %>
<p><%= user.email %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcSiteForEx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/history.html.erb
<div class='container'>
  <h1>購入履歴</h1>
  <% current_user.items.group_by(&:itself).each do |item, array| %>
    <p><%= item.name %> <%= array.count %></p>
  <% end %>
</div>